### ISSUE TITLE
Maintenance - Update to Barrio 5.5.5

### ISSUE THREAD

**Issue by meschenbaum** [cu-uis/cu_base#19]
**Describe the update**
Barrio theme just released 5.5.5 that has a lot of updates to including webform and media. We will need to update our theme to support this latest version.

**Comment by kreynen** [comment]
Just adding a note here so I'm not the only one who knew this at one point and forgets about it. I pinned online.cu.edu to 5.5.4 in https://gitlab.cu.edu/uis-webdev/online-cu-starterkit/-/blob/master/composer.json#L328.  That site will stay on 5.5.4 regardless of what happens in the upstream until that line is removed from the root/project level composer.json.
